13:4: not a valid test operator: (
13:4: not a valid test operator: 525.85.12
Downloading: "https://download.pytorch.org/models/googlenet-1378be20.pth" to /home/gharatappeh/.cache/torch/hub/checkpoints/googlenet-1378be20.pth
  0%|          | 0.00/49.7M [00:00<?, ?B/s]  4%|▍         | 2.17M/49.7M [00:00<00:02, 22.7MB/s] 14%|█▍        | 6.99M/49.7M [00:00<00:01, 37.9MB/s] 28%|██▊       | 14.1M/49.7M [00:00<00:00, 53.7MB/s] 39%|███▊      | 19.2M/49.7M [00:00<00:00, 46.6MB/s] 48%|████▊     | 23.7M/49.7M [00:00<00:00, 44.5MB/s] 56%|█████▋    | 28.1M/49.7M [00:00<00:00, 39.1MB/s] 69%|██████▉   | 34.4M/49.7M [00:00<00:00, 46.5MB/s] 80%|███████▉  | 39.7M/49.7M [00:00<00:00, 49.0MB/s] 90%|████████▉ | 44.7M/49.7M [00:01<00:00, 48.8MB/s]100%|██████████| 49.7M/49.7M [00:01<00:00, 47.5MB/s]
  0%|          | 0/10 [00:00<?, ?it/s]  0%|          | 0/10 [06:53<?, ?it/s]
Traceback (most recent call last):
  File "/home/gharatappeh/nips/src/prune.py", line 767, in <module>
    main()
  File "/home/gharatappeh/nips/src/prune.py", line 757, in main
    perf_exper(logger, args, device, run_dir)
  File "/home/gharatappeh/nips/src/prune.py", line 715, in perf_exper
    all_acc, conn = perf_lth(logger, device, args, controller)
  File "/home/gharatappeh/nips/src/prune.py", line 624, in perf_lth
    pruning.corrs.append(activations.get_corrs())
  File "/home/gharatappeh/nips/src/correlation.py", line 177, in get_corrs
    child_arr.append(self.activation[act_keys[idx + 1]].\
IndexError: list index out of range
